/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attention zones of the network, largest deviation first */
        get: operations["attention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the forecast as CSV (one row per stop and period) */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service metadata: current moment, selectable dates, horizons, data source */
        get: operations["meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast quality: WAPE of the initial daily forecasts against the facts */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast of every route, for painting the network map */
        get: operations["routes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{routeId}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast of one route with all of its stops */
        get: operations["routeForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{routeId}/load-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Typical week of a route: load by day of week and hour */
        get: operations["loadMatrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{routeId}/stops/{stopId}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stop details: baseline, deviation, status, peak, facts a year earlier, factors */
        get: operations["stopForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Attention: {
            /** Format: date */
            date?: string;
            horizon?: string;
            /** Format: date-time */
            lastUpdated?: string;
            zones?: components["schemas"]["AttentionZone"][];
        };
        AttentionZone: {
            /** Format: double */
            deviationAbs?: number;
            /** Format: double */
            deviationPct?: number;
            level?: string;
            /** Format: date-time */
            maxDeviationAt?: string;
            /** Format: date-time */
            peakAt?: string;
            recommendation?: components["schemas"]["Recommendation"];
            routeId?: string;
            stopId?: string;
        };
        DailyAccuracy: {
            /** Format: date */
            date?: string;
            /** Format: double */
            wape?: number;
            /** Format: double */
            wapeScore?: number;
        };
        HorizonInfo: {
            horizon?: string;
            step?: string;
        };
        LastYearPoint: {
            /** Format: date-time */
            periodStart?: string;
            /** Format: double */
            value?: number;
        };
        LoadMatrix: {
            cells?: components["schemas"]["MatrixCell"][];
            routeId?: string;
        };
        MatrixCell: {
            /** Format: int32 */
            dayOfWeek?: number;
            /** Format: int32 */
            hour?: number;
            /** Format: double */
            value?: number;
        };
        Meta: {
            dataSource?: string;
            horizons?: components["schemas"]["HorizonInfo"][];
            /** Format: date */
            latestDate?: string;
            /** Format: date-time */
            now?: string;
            /** Format: date */
            today?: string;
            zone?: string;
        };
        ModelStats: {
            history?: components["schemas"]["DailyAccuracy"][];
            /** Format: double */
            wape?: number;
            /** Format: double */
            wapeScore?: number;
        };
        NetworkOverview: {
            /** Format: date */
            date?: string;
            horizon?: string;
            /** Format: date-time */
            lastUpdated?: string;
            routes?: components["schemas"]["RouteSeries"][];
        };
        Point: {
            /** Format: double */
            actual?: number;
            /** Format: double */
            baseline?: number;
            /** Format: double */
            deviationAbs?: number;
            /** Format: double */
            deviationPct?: number;
            /** Format: double */
            forecast?: number;
            /** Format: date-time */
            periodStart?: string;
        };
        /** @description RFC 9457 problem document */
        Problem: {
            /**
             * @description Machine-readable error code, stable across releases (codes are added, never renamed)
             * @example ROUTE_NOT_FOUND
             * @enum {string}
             */
            code?: "INVALID_REQUEST" | "INVALID_PARAMETER" | "ROUTE_NOT_FOUND" | "STOP_NOT_FOUND" | "NO_DATA" | "ENDPOINT_NOT_FOUND" | "METHOD_NOT_ALLOWED" | "FORECAST_NOT_READY" | "UNAUTHORIZED" | "INTERNAL_ERROR";
            /**
             * @description A message that can be shown to the user
             * @example One of the request parameters is missing or has the wrong format.
             */
            detail?: string;
            /** @example /api/routes */
            instance?: string;
            /**
             * Format: int32
             * @example 400
             */
            status?: number;
            /**
             * @description When the error happened, ISO 8601 with an explicit offset
             * @example 2026-09-26T13:20:11.123+03:00
             */
            timestamp?: string;
            /** @example Invalid parameter */
            title?: string;
            /** @example about:blank */
            type?: string;
        };
        Recommendation: {
            action?: string;
            /** Format: int32 */
            vehicles?: number;
        };
        RouteForecast: {
            /** Format: date */
            date?: string;
            horizon?: string;
            /** Format: date-time */
            lastUpdated?: string;
            lastYear?: components["schemas"]["LastYearPoint"][];
            points?: components["schemas"]["Point"][];
            routeId?: string;
            stops?: components["schemas"]["StopSeries"][];
        };
        RouteSeries: {
            points?: components["schemas"]["SlimPoint"][];
            routeId?: string;
        };
        SlimPoint: {
            /** Format: double */
            baseline?: number;
            /** Format: double */
            forecast?: number;
            /** Format: date-time */
            periodStart?: string;
        };
        StopForecast: {
            /** Format: date */
            date?: string;
            factors?: string[];
            horizon?: string;
            /** Format: date-time */
            lastUpdated?: string;
            lastYear?: components["schemas"]["LastYearPoint"][];
            /** Format: date-time */
            maxDeviationAt?: string;
            modelVersion?: string;
            /** Format: date-time */
            peakAt?: string;
            points?: components["schemas"]["Point"][];
            recommendation?: components["schemas"]["Recommendation"];
            routeId?: string;
            status?: string;
            stopId?: string;
        };
        StopSeries: {
            points?: components["schemas"]["SlimPoint"][];
            stopId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    attention: {
        parameters: {
            query?: {
                /** @description Planning horizon. It fixes the step of the returned points: day = hourly, week = daily (seven days starting at the anchor date), month = daily, year = monthly. */
                horizon?: "day" | "week" | "month" | "year";
                /**
                 * @description Anchor date YYYY-MM-DD: the day itself; the first of the seven days of a week; or any day inside the month or year. Defaults to today, at most one year ahead.
                 * @example 2026-09-25
                 */
                date?: string;
                /** @description Which stored snapshot to read: the latest one, or the initial one (the forecast as it was first made for that date). */
                snapshot?: "latest" | "initial";
                /** @description Weather correction multiplier applied to the forecast. */
                weather?: number;
                /** @description Event correction multiplier applied to the forecast. */
                event?: number;
                /** @description Season correction multiplier applied to the forecast. */
                season?: number;
                /**
                 * @description Inclusive lower bound of the returned periods, ISO 8601 with offset.
                 * @example 2026-09-25T06:00:00+03:00
                 */
                from?: string;
                /**
                 * @description Exclusive upper bound of the returned periods, ISO 8601 with offset.
                 * @example 2026-09-25T12:00:00+03:00
                 */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attention"];
                };
            };
            /** @description Invalid parameter or request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or invalid Authorization: Basic header (only when access control is on) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No forecast is stored for the request and the ML service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: {
                format?: string;
                routeId?: string;
                stopId?: string;
                /** @description Planning horizon. It fixes the step of the returned points: day = hourly, week = daily (seven days starting at the anchor date), month = daily, year = monthly. */
                horizon?: "day" | "week" | "month" | "year";
                /**
                 * @description Anchor date YYYY-MM-DD: the day itself; the first of the seven days of a week; or any day inside the month or year. Defaults to today, at most one year ahead.
                 * @example 2026-09-25
                 */
                date?: string;
                /** @description Which stored snapshot to read: the latest one, or the initial one (the forecast as it was first made for that date). */
                snapshot?: "latest" | "initial";
                /** @description Weather correction multiplier applied to the forecast. */
                weather?: number;
                /** @description Event correction multiplier applied to the forecast. */
                event?: number;
                /** @description Season correction multiplier applied to the forecast. */
                season?: number;
                /**
                 * @description Inclusive lower bound of the returned periods, ISO 8601 with offset.
                 * @example 2026-09-25T06:00:00+03:00
                 */
                from?: string;
                /**
                 * @description Exclusive upper bound of the returned periods, ISO 8601 with offset.
                 * @example 2026-09-25T12:00:00+03:00
                 */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A CSV attachment, UTF-8, header row first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Invalid parameter or request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or invalid Authorization: Basic header (only when access control is on) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unknown route or stop, or nothing to return for them */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No forecast is stored for the request and the ML service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            /** @description Missing or invalid Authorization: Basic header (only when access control is on) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStats"];
                };
            };
            /** @description Invalid parameter or request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or invalid Authorization: Basic header (only when access control is on) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    routes: {
        parameters: {
            query?: {
                /** @description Planning horizon. It fixes the step of the returned points: day = hourly, week = daily (seven days starting at the anchor date), month = daily, year = monthly. */
                horizon?: "day" | "week" | "month" | "year";
                /**
                 * @description Anchor date YYYY-MM-DD: the day itself; the first of the seven days of a week; or any day inside the month or year. Defaults to today, at most one year ahead.
                 * @example 2026-09-25
                 */
                date?: string;
                /** @description Which stored snapshot to read: the latest one, or the initial one (the forecast as it was first made for that date). */
                snapshot?: "latest" | "initial";
                /** @description Weather correction multiplier applied to the forecast. */
                weather?: number;
                /** @description Event correction multiplier applied to the forecast. */
                event?: number;
                /** @description Season correction multiplier applied to the forecast. */
                season?: number;
                /**
                 * @description Inclusive lower bound of the returned periods, ISO 8601 with offset.
                 * @example 2026-09-25T06:00:00+03:00
                 */
                from?: string;
                /**
                 * @description Exclusive upper bound of the returned periods, ISO 8601 with offset.
                 * @example 2026-09-25T12:00:00+03:00
                 */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkOverview"];
                };
            };
            /** @description Invalid parameter or request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or invalid Authorization: Basic header (only when access control is on) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No forecast is stored for the request and the ML service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    routeForecast: {
        parameters: {
            query?: {
                /** @description Planning horizon. It fixes the step of the returned points: day = hourly, week = daily (seven days starting at the anchor date), month = daily, year = monthly. */
                horizon?: "day" | "week" | "month" | "year";
                /**
                 * @description Anchor date YYYY-MM-DD: the day itself; the first of the seven days of a week; or any day inside the month or year. Defaults to today, at most one year ahead.
                 * @example 2026-09-25
                 */
                date?: string;
                /** @description Which stored snapshot to read: the latest one, or the initial one (the forecast as it was first made for that date). */
                snapshot?: "latest" | "initial";
                /** @description Weather correction multiplier applied to the forecast. */
                weather?: number;
                /** @description Event correction multiplier applied to the forecast. */
                event?: number;
                /** @description Season correction multiplier applied to the forecast. */
                season?: number;
                /**
                 * @description Inclusive lower bound of the returned periods, ISO 8601 with offset.
                 * @example 2026-09-25T06:00:00+03:00
                 */
                from?: string;
                /**
                 * @description Exclusive upper bound of the returned periods, ISO 8601 with offset.
                 * @example 2026-09-25T12:00:00+03:00
                 */
                to?: string;
            };
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteForecast"];
                };
            };
            /** @description Invalid parameter or request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or invalid Authorization: Basic header (only when access control is on) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unknown route or stop, or nothing to return for them */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No forecast is stored for the request and the ML service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    loadMatrix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadMatrix"];
                };
            };
            /** @description Invalid parameter or request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or invalid Authorization: Basic header (only when access control is on) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unknown route or stop, or nothing to return for them */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stopForecast: {
        parameters: {
            query?: {
                /** @description Planning horizon. It fixes the step of the returned points: day = hourly, week = daily (seven days starting at the anchor date), month = daily, year = monthly. */
                horizon?: "day" | "week" | "month" | "year";
                /**
                 * @description Anchor date YYYY-MM-DD: the day itself; the first of the seven days of a week; or any day inside the month or year. Defaults to today, at most one year ahead.
                 * @example 2026-09-25
                 */
                date?: string;
                /** @description Which stored snapshot to read: the latest one, or the initial one (the forecast as it was first made for that date). */
                snapshot?: "latest" | "initial";
                /** @description Weather correction multiplier applied to the forecast. */
                weather?: number;
                /** @description Event correction multiplier applied to the forecast. */
                event?: number;
                /** @description Season correction multiplier applied to the forecast. */
                season?: number;
                /**
                 * @description Inclusive lower bound of the returned periods, ISO 8601 with offset.
                 * @example 2026-09-25T06:00:00+03:00
                 */
                from?: string;
                /**
                 * @description Exclusive upper bound of the returned periods, ISO 8601 with offset.
                 * @example 2026-09-25T12:00:00+03:00
                 */
                to?: string;
            };
            header?: never;
            path: {
                routeId: string;
                stopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopForecast"];
                };
            };
            /** @description Invalid parameter or request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or invalid Authorization: Basic header (only when access control is on) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unknown route or stop, or nothing to return for them */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No forecast is stored for the request and the ML service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
